### ISSUE TITLE
load a volume

### ISSUE THREAD

**Issue by pipemg** [QuantumObject/docker-rstudio#6]
I cant load a volume to be use in the R-studio server

**Comment by angelrr7702** [comment]
did you can provide more detail ? where you try to mount the volume. My R-studio  container used regular user linux account for user ...   it come with guest account  ... mean that /home/guest/  if you choose to delete guest users and add other user , path for that user will be at /home/..../

**Comment by pipemg** [comment]
sorry, yes I kow that, the main problem are the permissions, even using UID=$UID and USER=$USER
